Web/Models/User/AuthViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.Models.User;

public class AuthViewModel
{
    [Required(ErrorMessage = "{0} is required")]
    [DataType(DataType.EmailAddress)]
    public string Email { get; set; }

    
    [Required(ErrorMessage = "{0} is required")]
    [DataType(DataType.Password)]
    public string Password { get; set; }
}

Web/Models/User/TokenViewModel.cs
namespace Web.Models.User;

public class TokenViewModel
{
    public string Name { get; set; }
    public string Email { get; set; }
    public string Token { get; set; }
}

Web/Models/User/UpdatePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.Models.User;

public class UpdatePasswordViewModel
{
    [Required(ErrorMessage = "{0} is required")]
    public string CurrentPassword { get; set; }

    [Required(ErrorMessage = "{0} is required")]
    public string NewPassword { get; set; }
}

Web/Models/User/UserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.Models.User;

public class UserViewModel
{
    [Required(ErrorMessage =  "{0} is required")]
    [StringLength(30, MinimumLength = 3)]
    public string Name { get; set; }
    [Required(ErrorMessage = "{0} is requerid")]
    [StringLength(30, MinimumLength = 3)]
    public string Surname { get; set; }
    [Required(ErrorMessage = "{0} is required")]
    [StringLength(250)]
    public string Email { get; set; }
    [Required(ErrorMessage = "{0} is required")]
    public string Password { get; set; }
}

Web/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Web.Models.Post;
using Web.Services.Contracts;

namespace Web.Controllers;

public class PostController : Controller
{
    private readonly IPostService _postService;
    private string token = string.Empty;
    public PostController(IPostService postService)
    {
        _postService = postService; 
    }

    [HttpGet]
    public async Task<ActionResult<IEnumerable<GetPostsViewModel>>> Index()
    {
        var response = await _postService.GetAll(); 
        if(response is null)
            return View("Error"); 

        if(!response.Any())
            return Redirect("/"); 
        return View(response); 
    }

    [HttpGet]
    public IActionResult NewPost()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult<GetPostViewModel>> NewPost(CreatePostViewModel model)
    {
        if(!ModelState.IsValid)
        {
            return View("Error"); 
        }
        var response = await _postService.CreateAsync(model, GetToken()); 
        if(response is null)
        {
            return View("Error"); 
        }
        return RedirectToAction(nameof(Index)); 
    }

    [HttpGet]
    public async Task<ActionResult<GetPostsViewModel>> MyPosts()
    {
        var response = await _postService.GetAllUser(GetToken());
        if(response is null)
        {
            return View("Error"); 
        }
        if(!response.Any())
            return RedirectToAction(nameof(NewPost));
        return View(response); 
    }

    [HttpGet]
    public async Task<ActionResult> Details(int id) 
    {
        var response = await _postService.DetailsAsynct(GetToken(), id); 
        if(response is null)
        {
            return View("Error"); 
        }
        return View(response); 
    }

    [HttpGet]
    public async Task<ActionResult> Edit(int id)
    {
        var response = await _postService.GetByIdAsync(id, GetToken()); 
        if(response is null)
        {
            return View("Error"); 
        }
        return View(response);      
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> Edit(int id, CreatePostViewModel model)
    {
        if(!ModelState.IsValid)
        {
            return View();
        }
        var response = await _postService.UpdateAsync(id, model, GetToken()); 
        if(!response)
            return View("Error"); 
        return RedirectToAction(nameof(MyPosts)); 
    }

    [HttpGet]
    public async Task<ActionResult> Delete(int id)
    {
        var response = await _postService.GetByIdAsync(id, GetToken());
        if(response is null)
            return View("Error"); 
        return View(response); 
    }

    [HttpPost(), ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> DeleteConfirmed(int id)
    {
        var response = await _postService.RemoveAsync(id, GetToken()); 
        if(!response)
            return View("Error"); 
        return RedirectToAction(nameof(MyPosts));
    }

    private string GetToken()
    {
        if(HttpContext.Request.Cookies.ContainsKey("access-token"))
            token = HttpContext.Request.Cookies["access-token"].ToString(); 
        return token; 
    }
}

Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Web.Models.User;
using Web.Services.Contracts;

namespace Web.Controllers;

public class UserController : Controller
{
    private readonly IAccountService _accountService;
    private readonly IAuthenticateService _authenticateService;
    private string token = string.Empty; 
    public UserController(IAccountService accountService, 
        IAuthenticateService authenticateService)
    {
        _accountService = accountService; 
        _authenticateService = authenticateService; 
    }

    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }

    [HttpPost]
    public async Task<ActionResult> Login(AuthViewModel model)
    {
        if(!ModelState.IsValid)
        {
            return View(model); 
        }
        var response = await _authenticateService.LoginAsync(model); 
        if(response is null)
        {
            return View("Error");    
        }
        Response.Cookies.Append("access-token", response.Token, new CookieOptions()
        {
            HttpOnly = true,
            SameSite = SameSiteMode.Strict
        });
        return Redirect("/");
    }

    [HttpGet]
    public IActionResult CreateAccount()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> CreateAccount(UserViewModel model)
    {
        if(!ModelState.IsValid)
        {   
            ModelState.AddModelError(string.Empty, "Invalid request..."); 
            return View(); 
        }
        var response = await _accountService.CreateAccountAsync(model);
        if(response is null)
        {
            return View("Error"); 
        } 
        return RedirectToAction(nameof(Login)); 

    }

    [HttpGet] 
    public async Task<ActionResult> GetProfile()
    {
        var response = await _accountService.GetProfileAsync(GetToken());
        if(response is null)
        {
            return View("Error"); 
        }
        return View(response); 
    }

    [HttpGet]
    public IActionResult UpdatePassword()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<ActionResult> UpdatePassword(UpdatePasswordViewModel model)
    {
        if(!ModelState.IsValid)
        { 
            return View();
        }
        var response = await _accountService.UpdatePasswordAsync(GetToken(), model);
        if(!response)
        {
            return View("Error"); 
        } 
        return Redirect("/");
    }    

    [HttpGet]
    public IActionResult Logout()
    {
        Response.Cookies.Delete("access-token"); 
        return RedirectToAction(nameof(Login)); 

    }
   
    private string GetToken()
    {
        if(HttpContext.Request.Cookies.ContainsKey("access-token"))
            token = HttpContext.Request.Cookies["access-token"].ToString(); 
        return token; 
    }

}

Web/Views/User/CreateAccount.cshtml
@model UserViewModel

@{
    ViewData["Title"] = "Create"; 
}

<h2>@ViewData["Title"]</h2>

<div class="row">
    <div class="col-md-8">
        <form asp-action="CreateAccount" method="post" class="form-horizontal">
            <div asp-validation-summary="All" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <div class="col-md-6">
                    <input type="text" asp-for="Name" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <div class="col-md-6">
                    <input type="text" asp-for="Surname" class="form-control">
                </div>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <div class="col-md-6">
                    <input type="text" asp-for="Email" class="form-control">
                </div>
            </div>

            <div class="form-group mb-2">
                <label asp-for="Password" class="control-label"></label>
                <div class="col-md-6">
                    <input type="password" asp-for="Password" class="form-control">
                </div>
            </div>

            <div class="form-group col-md-6">
                <div>
                    <button type="submit" class="btn btn-outline-dark">Create Account</button>
                </div>
            </div>
        </form>
    </div>
</div>

Web/Views/User/GetProfile.cshtml
@model UserViewModel 

@{
    ViewData["Title"] = "Your Profile"; 
    string name = $"{Model.Name} {Model.Surname}"; 
}

<h2>@ViewData["Title"]</h2>

<div class="card">
    <div class="card-body">
        <h3>Welcome again @name !</h3>
        <h4>Your email: @Model.Email</h4>
    </div>
</div>

Web/Views/User/Index.cshtml
@model UserViewModel

<h2>@ViewData["Title"]</h2>

<div class="container d-flex flex-row">
    <div class="bg-primary">
        
    </div>
    <div>
        <form asp-action="Login" method="post">  
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <div class="col-md-10">
                    <input type="text" class="form-control">
                </div>
            </div>

            <div class="form-group" style="margin-bottom: 10px">
                <label asp-for="Password" class="control-label"></label>
                <div class="col-md-10">
                    <input type="password" class="form-control">
                </div>
            </div>
        
            <div class="form-group d-flex">
                <div class="">
                    <button type="submit" class="btn btn-outline-dark">
                        Login
                    </button>
                </div>

                <div class="ms-2">
                    <a asp-action="CreateAccount" class="btn btn-outline-dark">Create account</a>
                </div>
            </div>

        </form>
    </div>
</div>

Web/Views/User/Login.cshtml
@model Web.Models.User.UserViewModel

<h2>Login</h2>

<div class="container d-flex flex-row">
    <div>
        <form asp-controller="User" asp-action="Login" method="post">  
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Email" type="email" class="form-control">
                </div>
            </div>

            <div class="form-group" style="margin-bottom: 10px">
                <label asp-for="Password" class="control-label"></label>
                <div class="col-md-10">
                    <input asp-for="Password" type="password" class="form-control">
                </div>
            </div>
        
            <div class="form-group d-flex">
                <div class="">
                    <button type="submit" class="btn btn-outline-dark">
                        Login
                    </button>
                </div>

                <div class="ms-2">
                    <a asp-action="CreateAccount" class="btn btn-outline-dark">Create account</a>
                </div>
            </div>

        </form>
    </div>
</div>

Web/Views/User/UpdatePassword.cshtml
@model UpdatePasswordViewModel 

@{
    ViewData["Title"] = "Update Password"; 
}

<h2>@ViewData["Title"]</h2>

<div class="container d-flex flex-row">
    <div>
        <form asp-controller="User" asp-action="UpdatePassword" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="CurrentPassword" class="control-label"></label>
                <div class="col-md-10">
                    <input asp-for="CurrentPassword" type="password" class="form-control">
                </div>
            </div>

            <div class="form-group" style="margin-bottom: 10px;">
                <label asp-for="NewPassword" class="control-label"></label>
                <div class="col-md-10">
                    <input asp-for="NewPassword" type="password" class="form-control">
                </div>
            </div>

            <div class="form-group d-flex">
                <div class="me-2">
                    <button type="submit" class="btn btn-outline-warning">
                        Update
                    </button>
                </div>
                <div>
                    <a asp-action="Index" asp-controller="Post" class="btn btn-outline-info">
                        Back
                    </a>
                </div>
            </div>

        </form>
    </div>
</div>